### ISSUE TITLE
[repo] Pacman error upgrade

### ISSUE THREAD

**Issue by Trinki79** [winesapOS/winesapOS#944] opened 2024-08-24 05:00 UTC
*During the software update phase, when it comes to updating pacman it gives an error and no longer continues. Complete log post

Package databases already synchronized
flatpak update -y com.usebottles.bottles.Locale/x86_64/stable --system --no-related --no-deps

Looking for updates?
1.	   	com.usebottles.bottles.Locale	stable	u	flathub	< 1.0?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y org.gnome.Cheese.Locale/x86_64/stable --system --no-related --no-deps

Looking for updates?
1.	   	org.gnome.Cheese.Locale	stable	u	flathub	< 1.9?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y org.filezillaproject.Filezilla.Locale/x86_64/stable --system --no-related --no-deps

Looking for updates?
1.	   	org.filezillaproject.Filezilla.Locale	stable	u	flathub	< 4.0?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y org.gnome.Platform.Locale/x86_64/45 --system --no-related --no-deps

Looking for updates?
1.	   	org.gnome.Platform.Locale	45	u	flathub	< 382.1?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y org.gnome.Platform.Locale/x86_64/46 --system --no-related --no-deps

Looking for updates?
1.	   	org.gnome.Platform.Locale	46	u	flathub	< 380.0?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y org.kde.Platform.Locale/x86_64/6.6 --system --no-related --no-deps

Looking for updates?
1.	   	org.kde.Platform.Locale	6.6	u	flathub	< 393.3?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y net.lutris.Lutris.Locale/x86_64/stable --system --no-related --no-deps

Looking for updates?
1.	   	net.lutris.Lutris.Locale	stable	u	flathub	< 9.0?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y com.obsproject.Studio.Locale/x86_64/stable --system --no-related --no-deps

Looking for updates?
1.	   	com.obsproject.Studio.Locale	stable	u	flathub	< 47.0?kB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
flatpak update -y org.videolan.VLC.Locale/x86_64/stable --system --no-related --no-deps

Looking for updates?
1.	   	org.videolan.VLC.Locale	stable	u	flathub	< 14.1?MB (partial)
Updating?
Updating?                        0%  0 bytes/s
Updating? ???????????????????? 100%
Updates complete.
Package databases already synchronized
Package databases already synchronized
git clone https://aur.archlinux.org/pacman-static.git --depth=1 /tmp/bauh@winesap/arch/build_1724475172/pacman-static

Cloning into '/tmp/bauh@winesap/arch/build_1724475172/pacman-static'...
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Using custom makepkg.conf -> /home/winesap/.config/bauh/arch/makepkg.conf
makepkg -ALcfm --check --noarchive --nobuild --noprepare --nodeps --config=/home/winesap/.config/bauh/arch/makepkg.conf

==> Making package: pacman-static 6.1.0-11 (Sat Aug 24 06:52:56 2024)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
-> Downloading pacman-6.1.0.tar.xz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   169    0   169    0     0   1133      0 --:--:-- --:--:-- --:--:--  1141
12  874k   12  107k    0     0   345k      0  0:00:02 --:--:--  0:00:02  345k
100  874k  100  874k    0     0  2123k      0 --:--:-- --:--:-- --:--:-- 7598k
-> Downloading pacman-6.1.0.tar.xz.sig...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   173    0   173    0     0   1137      0 --:--:-- --:--:-- --:--:--  1138
100   310  100   310    0     0   1481      0 --:--:-- --:--:-- --:--:--  1481
-> Downloading revertme-makepkg-remove-libdepends-and-libprovides.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5738    0  5738    0     0  26083      0 --:--:-- --:--:-- --:--:-- 26200
-> Downloading pacman-static-fix-msg-unknown-key.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1550    0  1550    0     0   8431      0 --:--:-- --:--:-- --:--:--  8469
-> Downloading pacman-static-man-gitlab.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2001    0  2001    0     0  12845      0 --:--:-- --:--:-- --:--:-- 12909
-> Downloading pacman-static-make-aligned-titles.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1160    0  1160    0     0   3803      0 --:--:-- --:--:-- --:--:--  3803
-> Downloading pacman-static-repo-add-parseopts.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1381    0  1381    0     0   8078      0 --:--:-- --:--:-- --:--:--  8123
-> Downloading pacman-static-drop-result-warn.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1100    0  1100    0     0   6542      0 --:--:-- --:--:-- --:--:--  6547
-> Downloading pacman-static-fix-debugedit.patch...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1575    0  1575    0     0  10298      0 --:--:-- --:--:-- --:--:-- 10361
-> Downloading nghttp2-1.62.1.tar.xz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1568k  100 1568k    0     0  2213k      0 --:--:-- --:--:-- --:--:-- 2213k
-> Downloading c-ares-1.33.0.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1016k  100 1016k    0     0  2394k      0 --:--:-- --:--:-- --:--:-- 2394k
-> Downloading c-ares-1.33.0.tar.gz.asc...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   228  100   228    0     0    330      0 --:--:-- --:--:-- --:--:--   330
-> Downloading curl-8.9.1.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   312  100   312    0     0   3205      0 --:--:-- --:--:-- --:--:--  3216
100 4101k  100 4101k    0     0  19.8M      0 --:--:-- --:--:-- --:--:-- 19.8M
-> Downloading curl-8.9.1.tar.gz.asc...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   316  100   316    0     0   4204      0 --:--:-- --:--:-- --:--:--  4213
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   488  100   488    0     0   3542      0 --:--:-- --:--:-- --:--:-- 16827
-> Downloading openssl-3.3.1.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 17.2M  100 17.2M    0     0  19.5M      0 --:--:-- --:--:-- --:--:-- 19.5M
-> Downloading openssl-3.3.1.tar.gz.asc...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0  19462      0 --:--:-- --:--:-- --:--:-- 19833
-> Found ca-dir.patch
-> Found openssl-3.0.7-no-atomic.patch
-> Downloading zlib-1.3.1.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 13 1477k   13  202k    0     0   187k      0  0:00:07  0:00:01  0:00:06  188k
100 1477k  100 1477k    0     0  1061k      0  0:00:01  0:00:01 --:--:-- 1062k
-> Downloading zlib-1.3.1.tar.gz.asc...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   235  100   235    0     0    464      0 --:--:-- --:--:-- --:--:--   465
-> Cloning xz git repo...
Cloning into bare repository '/tmp/bauh@winesap/arch/build_1724475172/pacman-static/xz'...
-> Downloading bzip2-1.0.8.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 26  791k   26  210k    0     0   229k      0  0:00:03 --:--:--  0:00:03  229k
100  791k  100  791k    0     0   763k      0  0:00:01  0:00:01 --:--:--  763k
-> Downloading bzip2-1.0.8.tar.gz.sig...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   310  100   310    0     0    653      0 --:--:-- --:--:-- --:--:--   654
-> Downloading zstd-1.5.6.tar.zst...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0 1802k    0 15829    0     0  23735      0  0:01:17 --:--:--  0:01:17 23735
100 1802k  100 1802k    0     0  2490k      0 --:--:-- --:--:-- --:--:-- 31.1M
-> Downloading zstd-1.5.6.tar.zst.sig...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   858  100   858    0     0   2211      0 --:--:-- --:--:-- --:--:--  2211
-> Downloading libgpg-error-1.50.tar.bz2...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 20 1056k   20  216k    0     0  1095k      0 --:--:-- --:--:-- --:--:-- 1090k
100 1056k  100 1056k    0     0  4261k      0 --:--:-- --:--:-- --:--:-- 4260k
-> Downloading libgpg-error-1.50.tar.bz2.sig...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   119  100   119    0     0   1154      0 --:--:-- --:--:-- --:--:--  1166
-> Downloading libassuan-3.0.0.tar.bz2...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  578k  100  578k    0     0  2530k      0 --:--:-- --:--:-- --:--:-- 2537k
-> Downloading libassuan-3.0.0.tar.bz2.sig...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   119  100   119    0     0   1183      0 --:--:-- --:--:-- --:--:--  1190
-> Downloading gpgme-1.23.2.tar.bz2...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1793k  100 1793k    0     0  6821k      0 --:--:-- --:--:-- --:--:-- 6846k
-> Downloading gpgme-1.23.2.tar.bz2.sig...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   238  100   238    0     0   2324      0 --:--:-- --:--:-- --:--:--  2333
-> Downloading libarchive-3.7.4.tar.xz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5290k  100 5290k    0     0  7020k      0 --:--:-- --:--:-- --:--:-- 7020k
-> Downloading libarchive-3.7.4.tar.xz.asc...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   659  100   659    0     0    958      0 --:--:-- --:--:-- --:--:--  1651
==> Validating source files with sha512sums...
pacman-6.1.0.tar.xz ... Passed
pacman-6.1.0.tar.xz.sig ... Skipped
revertme-makepkg-remove-libdepends-and-libprovides.patch ... Passed
pacman-static-fix-msg-unknown-key.patch ... Passed
pacman-static-man-gitlab.patch ... Passed
pacman-static-make-aligned-titles.patch ... Passed
pacman-static-repo-add-parseopts.patch ... Passed
pacman-static-drop-result-warn.patch ... Passed
pacman-static-fix-debugedit.patch ... Passed
nghttp2-1.62.1.tar.xz ... Passed
c-ares-1.33.0.tar.gz ... Passed
c-ares-1.33.0.tar.gz.asc ... Skipped
curl-8.9.1.tar.gz ... Passed
curl-8.9.1.tar.gz.asc ... Skipped
openssl-3.3.1.tar.gz ... Passed
openssl-3.3.1.tar.gz.asc ... Skipped
ca-dir.patch ... Passed
openssl-3.0.7-no-atomic.patch ... Passed
zlib-1.3.1.tar.gz ... Passed
zlib-1.3.1.tar.gz.asc ... Skipped
xz ... Passed
bzip2-1.0.8.tar.gz ... Passed
bzip2-1.0.8.tar.gz.sig ... Skipped
zstd-1.5.6.tar.zst ... Passed
zstd-1.5.6.tar.zst.sig ... Skipped
libgpg-error-1.50.tar.bz2 ... Passed
libgpg-error-1.50.tar.bz2.sig ... Skipped
libassuan-3.0.0.tar.bz2 ... Passed
libassuan-3.0.0.tar.bz2.sig ... Skipped
gpgme-1.23.2.tar.bz2 ... Passed
gpgme-1.23.2.tar.bz2.sig ... Skipped
libarchive-3.7.4.tar.xz ... Passed
libarchive-3.7.4.tar.xz.asc ... Skipped
==> Verifying source file signatures with gpg...
pacman-6.1.0.tar.xz ... Passed
c-ares-1.33.0.tar.gz ... Passed
curl-8.9.1.tar.gz ... FAILED (unknown public key 5CC908FDB71E12C2)
openssl-3.3.1.tar.gz ... FAILED (unknown public key D894E2CE8B3D79F5)
zlib-1.3.1.tar.gz ... FAILED (unknown public key 783FCD8E58BCAFBA)
bzip2-1.0.8.tar.gz ... FAILED (unknown public key FC57E3CCACD99A78)
zstd-1.5.6.tar.zst ... FAILED (unknown public key EF8FE99528B52FFD)
libgpg-error-1.50.tar.bz2 ... FAILED (unknown public key 528897B826403ADA)
libassuan-3.0.0.tar.bz2 ... FAILED (unknown public key 528897B826403ADA)
gpgme-1.23.2.tar.bz2 ... FAILED (unknown public key E98E9B2D19C6C8BD)
libarchive-3.7.4.tar.xz ... FAILED (unknown public key 5848A18B8F14184B)
==> ERROR: One or more PGP signatures could not be verified!
gpg --keyserver keyserver.ubuntu.com --recv-key 5CC908FDB71E12C2

gpg: key 5CC908FDB71E12C2: public key "Daniel Stenberg <daniel@haxx.se>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Using custom makepkg.conf -> /home/winesap/.config/bauh/arch/makepkg.conf
makepkg -ALcsmf --skipchecksums --nodeps --config=/home/winesap/.config/bauh/arch/makepkg.conf

==> Making package: pacman-static 6.1.0-11 (Sat Aug 24 06:53:18 2024)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
-> Found pacman-6.1.0.tar.xz
-> Found pacman-6.1.0.tar.xz.sig
-> Found revertme-makepkg-remove-libdepends-and-libprovides.patch
-> Found pacman-static-fix-msg-unknown-key.patch
-> Found pacman-static-man-gitlab.patch
-> Found pacman-static-make-aligned-titles.patch
-> Found pacman-static-repo-add-parseopts.patch
-> Found pacman-static-drop-result-warn.patch
-> Found pacman-static-fix-debugedit.patch
-> Found nghttp2-1.62.1.tar.xz
-> Found c-ares-1.33.0.tar.gz
-> Found c-ares-1.33.0.tar.gz.asc
-> Found curl-8.9.1.tar.gz
-> Found curl-8.9.1.tar.gz.asc
-> Found openssl-3.3.1.tar.gz
-> Found openssl-3.3.1.tar.gz.asc
-> Found ca-dir.patch
-> Found openssl-3.0.7-no-atomic.patch
-> Found zlib-1.3.1.tar.gz
-> Found zlib-1.3.1.tar.gz.asc
-> Updating xz git repo...
-> Found bzip2-1.0.8.tar.gz
-> Found bzip2-1.0.8.tar.gz.sig
-> Found zstd-1.5.6.tar.zst
-> Found zstd-1.5.6.tar.zst.sig
-> Found libgpg-error-1.50.tar.bz2
-> Found libgpg-error-1.50.tar.bz2.sig
-> Found libassuan-3.0.0.tar.bz2
-> Found libassuan-3.0.0.tar.bz2.sig
-> Found gpgme-1.23.2.tar.bz2
-> Found gpgme-1.23.2.tar.bz2.sig
-> Found libarchive-3.7.4.tar.xz
-> Found libarchive-3.7.4.tar.xz.asc
==> WARNING: Skipping verification of source file checksums.
==> Verifying source file signatures with gpg...
pacman-6.1.0.tar.xz ... Passed
c-ares-1.33.0.tar.gz ... Passed
curl-8.9.1.tar.gz ... Passed
openssl-3.3.1.tar.gz ... FAILED (unknown public key D894E2CE8B3D79F5)
zlib-1.3.1.tar.gz ... FAILED (unknown public key 783FCD8E58BCAFBA)
bzip2-1.0.8.tar.gz ... FAILED (unknown public key FC57E3CCACD99A78)
zstd-1.5.6.tar.zst ... FAILED (unknown public key EF8FE99528B52FFD)
libgpg-error-1.50.tar.bz2 ... FAILED (unknown public key 528897B826403ADA)
libassuan-3.0.0.tar.bz2 ... FAILED (unknown public key 528897B826403ADA)
gpgme-1.23.2.tar.bz2 ... FAILED (unknown public key E98E9B2D19C6C8BD)
libarchive-3.7.4.tar.xz ... FAILED (unknown public key 5848A18B8F14184B)
==> ERROR: One or more PGP signatures could not be verified!
rm -rf /tmp/bauh@winesap/arch/build_1724475172

Package "pacman-static" upgrade failed

**Comment by LukeShortCloud** [comment] 2024-08-24 14:34
Thanks for reporting your issue. We'll help you get this figured out!

I have a few questions to help with reproducing and troubleshooting the issue:

- What version of winesapOS are you on? 4.1.0?
- What image type are you using? Minimal, Performance, or Secure?
- How are you doing the upgrade? With the "winesapOS Upgrade" desktop shortcut?

At a glance of your log, I'm seeing lots of system packages failing a PGP key check. For example: `libarchive`, `openssl`, `zstd`, and more. Updating the Arch Linux keyring package normally fixes that. It should automatically happen during a winesapOS Upgrade.

```
sudo pacman -S -y
sudo pacman -S archlinux-keyring
```

**Comment by GuestSneezeOSDev** [comment] 2024-08-24 17:03
@Trinki79 Could you mention which version of winesapOS you are using?

**Comment by Trinki79** [comment] 2024-08-24 18:49
hi, I use the 4.1.0 performance version. I used bauh to perform the update

**Comment by LukeShortCloud** [comment] 2024-08-25 02:13
Thanks for the information!

GUI package managers for Arch Linux are, unfortunately, not great.

We used to provide package upgrade support in Discover but had to remove it because it would upgrade one package at a time. If it failed to install even one package, it would stop the entire upgrade and leave your system in a half broken state.

bauh will at least upgrade all or nothing. It's not possible to be get in a half broken state, at least. I recommend bauh for installing new packages only (not for upgrades).

For full system upgrades, I recommend only using the "winesapOS Upgrade" desktop shortcut. It's a lot smarter and handles a lot more edge cases. It'll only upgrade the system if there is a new winesapOS version out. We just released 4.1.0 so it's very new. We aim to have a new release every 3-4 months.

**Comment by Trinki79** [comment] 2024-08-25 04:17
I removed the link to winesapOS Upgrade on the destop by mistake, how can I restore it?

**Comment by GuestSneezeOSDev** [comment] 2024-08-25 10:34
try running 
```
curl https://raw.githubusercontent.com/LukeShortCloud/winesapOS/main/scripts/winesapos-upgrade.sh | sudo bash
```

**Comment by LukeShortCloud** [comment] 2024-08-25 14:25
You can manually run the winesapOS Upgrade script at anytime using the one-liner that @GuestSneezeOSDev  provided.

You can also add the desktop shortcut back by running this command:

```

ln -s /home/winesap/.winesapos/winesapos-upgrade.desktop /home/winesap/Desktop/winesapos-upgrade.desktop
```

**Comment by Trinki79** [comment] 2024-08-26 04:11
Hi sorry if I reply now. With this command(
ln -s /home/winesap/.winesapos/winesapos-upgrade.desktop /home/winesap/Desktop/winesapos-upgrade.desktop) is restored. But it doesn't tell me about system updates, which instead are there with bauh.

**Comment by LukeShortCloud** [comment] 2024-08-26 17:38
winesapOS is based on Arch Linux. For advanced Linux users, they can get the latest Arch Linux updates by using the terminal/CLI. However, they must manually deal with any upgrade issues. Whenever there is a new winesapOS update, we automatically handle known upgrade issues in Arch Linux since our last release.

Long-term, we're working on an enhanced upgrade program that'll work on all Arch Linux systems including winesapOS. Soon you always have the latest up-to-date packages thanks to [archupgrade-go](https://github.com/ohaiibuzzle/archupgrade-go): https://github.com/LukeShortCloud/winesapOS/issues/711

**Comment by LukeShortCloud** [comment] 2024-10-17 22:09
This will be fixed by `archupgrade-go` where progress is being tracked here: https://github.com/winesapOS/winesapOS/issues/711

**Closed by LukeShortCloud** 2024-10-17 22:09 UTC
Labels: bug
